version: "3.5"

volumes:
        wordpress:
                name: wordpress
                driver: local
                driver_opts:
                        device: ~/Desktop/docker-inception/wordpress
                        o: bind
                        type: none
        mariadb:
                name: mariadb
                driver: local
                driver_opts:
                        device: ~/Desktop/docker-inception/mariadb
                        o: bind
                        type: none
        portainer_data:
                name: portainer
                driver: local
                driver_opts:
                        device: ~/Desktop/docker-inception/portainer
                        o: bind
                        type: none

networks:
  inception:
    name: inception

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    image: mariadb:42
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    image: wordpress:42
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    image: nginx:42
    ports:
     - "443:443"
    depends_on:
      - wordpress
    volumes:
     - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always
  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer/.
    image: adminer:42
    depends_on:
      - mariadb
      - wordpress
    ports:
      - "8080:8080"
    networks:
      - inception
    restart: always
  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp/.
    image: ftp:42
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    networks:
      - inception
    restart: always
  redis:
    container_name: redis
    build: ./requirements/bonus/redis/.
    image: redis:42
    volumes:
     - wordpress:/var/www/html
    depends_on:
      - wordpress
    env_file:
      - .env
    networks:
      - inception
    restart: always
  portainer:
    container_name: portainer
    build: "./requirements/bonus/portainer"
    ports:
      - "9443:9443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
    networks:
      - inception
    restart: always
  website:
    container_name: website
    build: ./requirements/bonus/website/.
    image: website:42
    ports:
      - "3000:3000"
    networks:
      - inception
    restart: always