FROM debian:buster

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install nodejs npm -y

COPY ./tools /home/app
WORKDIR /home/app

RUN npm init -y && npm install express -y

EXPOSE 3000

CMD ["node", "server.js"]